### ISSUE TITLE
Sentry docking keycloak problem

### ISSUE THREAD

**Issue by shaxiaozz** [enterdv/grafana-scripts#1]
Hi, I am facing the same problem as you in Keycloak 23.0.4 and would like to know what is your version of Keycloak?

I tried to find out your solution in Keycloak 23.0.4 this version:
Create firstName, lastName and email mappers fixed the issue
But I didn't find it, can you share it?

issues link：https://github.com/getsentry/self-hosted/issues/1571

I'm very sorry to disturb you.

**Comment by enterdv** [comment]
Hi, Unfortunately, I can no longer help. I no longer work for that company, sorry

**Comment by shaxiaozz** [comment]
thank you for your reply！~
